name: Auto Build Java

on: 
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - swagger-test/src/main/**
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  
concurrency:
  group: "build"
  cancel-in-progress: true

jobs: 
  buildjava:
    runs-on: ubuntu-latest
    environment:
      name: github-pages-swagger-ui-java
      url: ${{ steps.deployment.outputs.page_url }}swagger-ui-java
    steps: 
    - uses: actions/checkout@v4
      with: 
        path: main
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn --file main/swagger-test/pom.xml install
    - name: Checkout swagger-ui
      uses: actions/checkout@v4
      with:
        repository: swagger-api/swagger-ui
        ref: 'v5.2.0'
        path: swagger-ui
    - name: Modify Initializer.js       #修改swagger-initializer.js，替换使用的json文件
      run: sed -i 's$"https:\/\/petstore\.swagger\.io\/v2\/swagger\.json"$new URL\(location\)\.searchParams\.get\("q"\) \|\| "swagger\.json"$g' swagger-ui/dist/swagger-initializer.js
    - name: Make swagger-ui-java folder
      run: mkdir -p temp/swagger-ui-java
    - name: Move dist to swagger-ui-java
      run: cp swagger-ui/dist/* temp/swagger-ui-java
    - name: run jar file
      run: nohup java -jar main/swagger-test/target/swagger-test-1.0.0.jar &
    - name: get json file
      run: curl -o temp/swagger-ui-java/swagger.json http://127.0.0.1:8765/v3/api-docs
    - name: Setup Pages
      uses: actions/configure-pages@v4
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'temp'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
    - name: JUnit report with Maven     #mavenでJUnit reportを作成
      # if: always() 
      run: mvn -f main/swagger-test/pom.xml clean test surefire-report:report jacoco:report
    - name: Upload java Build results
      uses: actions/upload-artifact@v4
      with:
        name: publish-results
        path: |
          backend/target/*.jar
    - name: Upload java other-documents results
      # if: always() 
      uses: actions/upload-artifact@v4
      with:
        name: other-documents
        path: |
          jar
          main/swagger-test/target/reports
          main/swagger-test/target/site
          
