name: Generate OpenAPI Docs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4    #设置java环境
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven                  #使用maven缓存

      - name: Generate OpenAPI Docs
        run: |
          mvn --file main/swagger-test/pom.xml clean openapi:generate

      - name: Upload OpenAPI JSON
        uses: actions/upload-artifact@v4
        with:
          name: openapi-docs
          path: main/swagger-test/target/swagger.json
