name: Generate OpenAPI Docs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4    #设置java环境
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven                  #使用maven缓存

      - name: Generate OpenAPI spec
        run: |
          cd swagger-test
          mvn clean compile
          cp target/enunciate/openapi.json ./api-spec/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: swagger-docs
          path: swagger-test/api-spec/openapi.json
