name: Generate OpenAPI Docs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4    #设置java环境
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven                  #使用maven缓存

      - name: Generate OpenAPI spec
        run: |
          ./mvnw org.openapitools:openapi-generator-maven-plugin:generate \
            -DgeneratorName=spring \
            -Doutput=./swagger.json \
            -DinputSpec=swagger-test/src/main/resources/openapi.json \
            -DskipValidateSpec=true \
            -DapiTests=false \
            -DmodelTests=false
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: swagger-docs
          path: swagger.json
