name: Generate OpenAPI Docs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4    #设置java环境
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven                  #使用maven缓存

      - name: Generate OpenAPI Spec
        run: |
          mvn clean compile -DskipTests
          ls -la target/openapi/ # 验证文件存在

      - name: Generate HTML Docs
        uses: openapitools/openapi-generator-cli@v2
        with:
          generator-name: html
          input-spec: target/openapi/openapi.json
          output: generated-docs

      - name: Upload Documentation
        uses: actions/upload-artifact@v3
        with:
          name: api-docs
          path: generated-docs
