name: Generate OpenAPI Docs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4    #设置java环境
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven                  #使用maven缓存

      - name: Generate OpenAPI
        run: |
          # 使用 OpenAPI Generator 扫描代码生成文档
          docker run --rm -v $(pwd):/app -w /app openapitools/openapi-generator-cli generate \
            -i src/main/java/ -g spring \
            -o docs/openapi.json

      - name: Upload Documentation
        uses: actions/upload-artifact@v4
        with:
          name: api-docs
          path: docs
